groups:
  primaryHand:
    groups: {}
    items:
      rotationSegments:
        zDescription: When you rotate your hand; it enters different segments. Increasing
          the number of segments increases the number of things you can do with your
          hand. Decreasing the number of segments makes it easier to be precise. Remember
          that some segments are hard for a human hand to reach, so you need to keep
          that in mind when choosing this number. It is expected that some segments
          will be unused for this reason. Don't hurt yourself.
        zzzEmpty: {}
        yDefaultValue: '4'
        yOldValue: '4'
        value: '8'
      rotationOffset:
        zDescription: In radians. Adjust where the segments are slightly to cater
          to your hand's natural bias.
        zzzEmpty: {}
        yDefaultValue: '0'
        yOldValue: '0'
        value: '0.3'
  secondaryHand:
    groups: {}
    items:
      rotationSegments:
        zDescription: When you rotate your hand; it enters different segments. Increasing
          the number of segments increases the number of things you can do with your
          hand. Decreasing the number of segments makes it easier to be precise. Remember
          that some segments are hard for a human hand to reach, so you need to keep
          that in mind when choosing this number. It is expected that some segments
          will be unused for this reason. Don't hurt yourself.
        zzzEmpty: {}
        yDefaultValue: '4'
        yOldValue: '4'
        value: '8'
      rotationOffset:
        zDescription: In radians. Adjust where the segments are slightly to cater
          to your hand's natural bias.
        zzzEmpty: {}
        yDefaultValue: '0'
        yOldValue: '0'
        value: '0.3'
items: {}
